# Generated by Django 3.1.14 on 2022-08-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serpage', '0003_auto_20220809_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdata',
            options={},
        ),
    ]
